---
# tasks file for ansible-role-liota

- name: install Liota using pip package
  become: true
  pip:
    name: liota
    version: "{{ liota_version }}"
  when: liota_version != 'github'

- name: install Liota using pip from github
  become: true
  pip:
    name: "{{ liota_github_url }}@{{ liota_github_branch }}"
  when: liota_version == 'github'
